WDP210702-47 Add auto generating menu links
Varenthein/wdp-2107-02 pull request #47
Opened 2021-07-24 20:02 UTC by AnOlbr

Celem zadania było zmienienie sztywno wpisanych linków w menu bar na generowane z InitialState.
Dodałam kategorie "menu" do InitialState (poza Home) i zmieniłam kod w MenuBar na mapujący listę linków stamtąd.

2021-07-25 11:36 UTC, Varenthein requested changes
W centrali masz już dane o kategoriach. Są one w kolekcji `categories`. Nie ma wiec sensu robić specjalnego zbioru z samymi linkami. Skorzystaj od razu z `categories`.

Pamiętaj jednak, że nie powinnaś korzystać bezpośrednio z obiektu `initialState`. To są tylko dane startowe dla centrali, a potem mogą się nawet potencjalnie zmienić. Powinnaś wiec skorzystac ze stanu z centrali. Uzyc mapStateToProps i doprowadzić info o kategoriach do komponentu.

2021-07-25 12:19 UTC, AnOlbr commented
> W centrali masz już dane o kategoriach. Są one w kolekcji `categories`. Nie ma wiec sensu robić specjalnego zbioru z samymi linkami. Skorzystaj od razu z `categories`.

menu: furniture, chair, table, sofa, bedroom, blog 
kategorie: bed, chair, sofa, table, dining

To wcale nie jest to samo, pokrywa się tylko częściowo :/ 

> Pamiętaj jednak, że nie powinnaś korzystać bezpośrednio z obiektu `initialState`. To są tylko dane startowe dla centrali, a potem mogą się nawet potencjalnie zmienić. Powinnaś wiec skorzystac ze stanu z centrali. Uzyc mapStateToProps i doprowadzić info o kategoriach do komponentu.

Zrobiłam analogicznie do komponentu ProductSearch i jakoś tam było dobrze i jest na masterze i nie kazałeś zmieniać.

2021-07-26 08:21 UTC, Varenthein commented
> > W centrali masz już dane o kategoriach. Są one w kolekcji `categories`. Nie ma wiec sensu robić specjalnego zbioru z samymi linkami. Skorzystaj od razu z `categories`.
> 
> menu: furniture, chair, table, sofa, bedroom, blog
> kategorie: bed, chair, sofa, table, dining
> 
> To wcale nie jest to samo, pokrywa się tylko częściowo :/
> 
> > Pamiętaj jednak, że nie powinnaś korzystać bezpośrednio z obiektu `initialState`. To są tylko dane startowe dla centrali, a potem mogą się nawet potencjalnie zmienić. Powinnaś wiec skorzystac ze stanu z centrali. Uzyc mapStateToProps i doprowadzić info o kategoriach do komponentu.
> 

Ok, jeśli się różnią, to zróbmy tę nową kolekcję z linkami (tak jak to zrobiłaś), ale pboeraj te dane do komentu przy użyciu connectu.

> Zrobiłam analogicznie do komponentu ProductSearch i jakoś tam było dobrze i jest na masterze i nie kazałeś zmieniać.

Nie kazałem zmieniać, bo ja tego PR-a nie reviewowałem, ani nie mergowałem.  Review do tego taska robiła Paulina, a zmergowany został z tego co widzę przez Ciebie. Gdybym robił, to wskazałbym Ci tę samą uwagę. Uwagę, a nie błąd. Bo też nie jest to jakis błąd składniowy, co bardziej zła praktyka, która myli innych członków zespołu. Zobacz, że plik `initialState` nazwą i umiejscowieniem sugeruje, że to dane startowe dla Reduxa, a nagle importujesz tablicę z linkami, jak gdyby to był zwykły obiekt, kompletnie ignorująć tutaj Reduxa.

2021-07-26 18:21 UTC, AnOlbr commented
Rezygnuję z tego zadania

2021-07-26 19:19 UTC, closed without merging